/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface OInput {
    'autoComplete': any;
    'autoFocus': any;
    'disabled': boolean;
    'form': any;
    'innerRef': any;
    /**
    * Label text of the input
    */
    'label': string;
    'max': any;
    'maxLength': any;
    'min': any;
    'name': any;
    'onKeyDown': any;
    'onKeyPress': any;
    'onKeyUp': any;
    'pattern': any;
    /**
    * Text that shows before the input has a value.
    */
    'placeholder'?: string;
    'readOnly': any;
    'required': any;
    'spellCheck': any;
    'type': any;
    /**
    * The value of the input.
    */
    'value'?: string | null;
  }
}

declare global {


  interface HTMLOInputElement extends Components.OInput, HTMLStencilElement {}
  var HTMLOInputElement: {
    prototype: HTMLOInputElement;
    new (): HTMLOInputElement;
  };
  interface HTMLElementTagNameMap {
    'o-input': HTMLOInputElement;
  }
}

declare namespace LocalJSX {
  interface OInput extends JSXBase.HTMLAttributes<HTMLOInputElement> {
    'autoComplete'?: any;
    'autoFocus'?: any;
    'disabled'?: boolean;
    'form'?: any;
    'innerRef'?: any;
    /**
    * Label text of the input
    */
    'label'?: string;
    'max'?: any;
    'maxLength'?: any;
    'min'?: any;
    'name'?: any;
    'onKeyDown'?: any;
    'onKeyPress'?: any;
    'onKeyUp'?: any;
    'onOrangoBlur'?: (event: CustomEvent<any>) => void;
    'onOrangoChange'?: (event: CustomEvent<any>) => void;
    'onOrangoFocus'?: (event: CustomEvent<any>) => void;
    'onOrangoInput'?: (event: CustomEvent<any>) => void;
    'pattern'?: any;
    /**
    * Text that shows before the input has a value.
    */
    'placeholder'?: string;
    'readOnly'?: any;
    'required'?: any;
    'spellCheck'?: any;
    'type'?: any;
    /**
    * The value of the input.
    */
    'value'?: string | null;
  }

  interface IntrinsicElements {
    'o-input': OInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


